name: CI

on:
  push:
    branches:
      - master
    paths:
      - 'source/**'
      - 'data/**'
      - 'images/**'
      - 'sounds/**'
      - 'tests/**'
      - '.github/workflows/**'
      - '.github/path-filters.yml'
      - 'CMakeLists.txt'
      - 'CMakePresets.json'
      - 'overlays/**'
      - keys.txt
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'source/**'
      - 'data/**'
      - 'tests/**'
      - '.github/workflows/**'
      - '.github/path-filters.yml'
      - 'CMakeLists.txt'
      - 'CMakePresets.json'
      - 'overlays/**'
      - keys.txt
  workflow_dispatch:

permissions:
  contents: read
  actions: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  linux:
    name: Ubuntu 22.04 GL
    runs-on: ubuntu-22.04
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v5
        with:
          show-progress: false
          fetch-depth: '10'
      - name: Install development dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends libxmu-dev libxi-dev libgl-dev libglu1-mesa-dev libgles2-mesa-dev libminizip-dev libwayland-dev libxkbcommon-dev libegl1-mesa-dev libosmesa6 mesa-utils libglvnd-dev x11-utils catch2 libltdl-dev autoconf autoconf-archive automake libtool
      - name: Disable VM sound card
        run: |
          sudo sh -c 'echo "pcm.!default { type plug slave.pcm \"null\" }"  >> /etc/asound.conf'
      - name: Find cache keys
        run: |
          echo 'RESTORE_KEYS<<EOF' > restore_keys.txt
          git log --pretty=format:'${{ runner.os }}-22.04-GL-ci-%H' -n 10 | tail -n+2 >> restore_keys.txt
          echo -e '\nEOF' >> restore_keys.txt
          cat restore_keys.txt >> "$GITHUB_ENV"
          echo "CACHE_HASH=$(git log --no-merges --pretty=format:'%H' -n 1)" >> "$GITHUB_ENV"
      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1
        with:
          key: ${{ runner.os }}-22.04-GL-ci-${{ env.CACHE_HASH }}
          restore-keys: ${{ env.RESTORE_KEYS }}
          evict-old-files: '2d'
          append-timestamp: 'false'
      - name: Adjust version strings
        run: ./utils/cd_update_versions.sh
      - name: Setup vcpkg cache
        uses: TAServers/vcpkg-cache@v3
        id: vcpkg-cache
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: lukka/get-cmake@v4.2.3
      - uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: '89dc8be6dbcf18482a5a1bf86a2f4615c939b0fb'
      - name: Run CMake
        run: |
          cmake --preset linux-ci
          cmake --build build --preset linux-ci
          ctest --preset linux-ci
        env:
          VCPKG_BINARY_SOURCES: "clear;files,${{ steps.vcpkg-cache.outputs.path }},readwrite"
